config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  devise_for :users
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
       patch 'checked'
    end
  end
  resources :users, only: [:show]
  root to: "items#index"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :order
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user # Likeを経由してUserと多対多になる

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :category
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :day
  belongs_to_active_hash :delivery_charge

  validates :price, numericality: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' } # 半角数字の正規表現

  with_options presence: true do
    validates :images, :name, :text

    validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'は範囲内の金額で設定してください' }

    validates :status_id, :category_id, :prefecture_id, :day_id, :delivery_charge_id,
              numericality: { other_than: 0, message: 'を選択してください' }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_search, only: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @items = Item.where(checked: false).with_attached_images.includes(:order, :likes, :user).order('created_at DESC') # N+1問題対策、売却済商品は表示設定分
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @like = Like.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params, checked: false)
    if @item.save
      redirect_to root_path, notice: '出品が完了しました。'
    else
      @item.images = nil # 画像プレビューを空にする
      render :new
    end
  end

  def update
    if @item.update(item_params, checked: false)
      redirect_to item_path(@item.id), notice: '商品の編集が完了しました。'
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: '商品を削除しました。'
    else
      flash.now[:alart] = '削除できない商品です。'
      redirect_to root_path
    end
  end

  def search
    if !search_params.nil?
      keywords = search_params[:name_or_text_cont].split(/[\p{blank}\s]+/) # キーワードを分割した配列に入れ直し
      grouping_hash = keywords.reduce({}) { |hash, word| hash.merge(word => { name_or_text_cont: word }) } # 分割したキーワードをransackに渡すパラメーターに組み立て直す
      @search = Item.ransack({ combinator: 'and', groupings: grouping_hash }) # ransackにパラメーターを渡し、ヒットした値をオブジェクト化
      @items = @search.result(distinct: true).order('created_at DESC') # オブジェクトの結果をビューの@itemsに渡す
    else
      @search = Item.ransack(search_params)
      @items = @search.result(distinct: true).order('created_at DESC')
    end
  end

  def checked # 売却済商品の非表示を選択可能に
    @item = Item.find(params[:id])
    if @item.checked == true
      @item.update(checked: false)
      redirect_to item_path(@item.id), notice: '表示設定をしました。'
    elsif @item.checked == false
      @item.update(checked: true)
      redirect_to item_path(@item.id), notice: '非表示に設定しました。'
    else
      flash.now[:alart] = '非表示設定のできない商品です。'
      redirect_to item_path(@item.id)
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :text, :price, :status_id, :category_id, :prefecture_id, :day_id, :delivery_charge_id, images: []).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to root_path unless user_signed_in? && current_user.id == @item.user.id && @item.order.nil?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_params
    params.require(:q).permit(:name_or_text_cont)
  end

  def set_search
    @search = Item.ransack(params[:q])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: item_path(@item.id), local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <label for="item-image" class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </label>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', id:"item-image" %>
      </div>
      <%# 画像プレビュー %>
      <div id="image-list"></div> 
      <% @item.images.each do |image| %>
        <%= image_tag image, class: 'item-img' %>
      <% end %>
    </div>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <label for="item-name" class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </label>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <label for="item-info" class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </label>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" , rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <label for="item-category" class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {selected: @item.category_id}, {class:"select-box", id:"item-category"}) %>
        <label for="item-sales-status" class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {selected: @item.status_id}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <label for="item-shipping-fee-status" class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {selected: @item.delivery_charge_id}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <label for="item-prefecture" class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {selected: @item.prefecture_id}, {class:"select-box", id:"item-prefecture"}) %>
        <label for="item-scheduled-delivery" class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {selected: @item.day_id}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <label for="item-price">価格</label>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
    </div>

  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>  
  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          最大3%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>
      <%# 全商品の一覧 %>
      <%= render partial: "shared/item_lists", locals: { items: @items } %> 

      <%# 商品がない場合のダミー %>
      <% if @items == nil %>
        <li class='list'>
          <%= link_to '#' do %>
            <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                商品を出品してね！
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= item.likes.count %></span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>

    </ul>
  </div>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <%= link_to (image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon"), new_item_path %>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: items_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <label for="item-image" class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </label>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', id:"item-image" %>
      </div>
      <%# 画像プレビュー %>
      <div id="image-list"></div> 
        <% @item.images.each do |image| %>
          <%= image_tag image, class: 'item-img' %>
        <% end %>
    </div>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <label for="item-name" class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </label>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <label for="item-info" class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </label>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <label for="item-category" class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <label for="item-sales-status" class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <label for="item-shipping-fee-status" class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <label for="item-prefecture" class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <label for="item-scheduled-delivery" class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </label>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <label for="item-price">価格</label>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>
<div class='main'>  
 

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>商品検索結果</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%# 1枚目の画像のみ表示, S3移行前の画像はno_images.pngに差し替え %>
              <% if item.images.attached? && item.images.count > 0 %>
                <%= image_tag item.images.first, class:'item-img' %>
              <% else %>
                <%= image_tag 'no_images.png', class: 'item-img' %>
              <% end %>

              <%# 商品が売れている場合 %>
              <% if item.order != nil  %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
              <% end %>  

            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br>(税込み)</span>
                <div class='star-btn'>
                 <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
       <% end %> 
    </ul>
  </div>
</div>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%# 画像スライド表示, S3移行前の画像はno_images.pngに差し替え %>
      <% if @item.images.attached? %>
        <div class="previews">
          <ul class="slider">
            <% @item.images.each do |image| %>
              <li><%= image_tag image, class:'item-box-img' %></li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <%= image_tag 'no_images.png', class: 'item-box-img' %>
      <% end %>
      
      <%# 商品が売れている場合 %>
      <% if @item.order != nil %> 
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>  

    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <%# 商品が売れていない場合(出品者) %>
    <% if user_signed_in? && @item.user.id == current_user.id && @item.order == nil %>
      <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
    <% end %>
    <%# 商品が売れている場合(出品者)※一覧から非表示を選べるようにする %>
    <% if user_signed_in? && @item.user.id == current_user.id && @item.order != nil %>
      <% if @item.checked == false %>
        <%= link_to '一覧から非表示', checked_item_path(@item.id), method: :patch, class:'item-destroy' %>
      <% else %>
        <%= link_to '一覧に表示', checked_item_path(@item.id), method: :patch, class:'item-destroy' %>
      <% end %>
    <% end %>

    <%# 商品が売れていない場合(出品者以外) %>
    <% if user_signed_in? && @item.user.id != current_user.id && @item.order == nil %>
      <%= link_to '購入画面に進む', item_orders_path(@item.id), class:"item-red-btn"%>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.delivery_charge.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.day.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <button class="favorite-btn">
        <%# お気に入り登録の有無で表示を分岐 %>
        <% if user_signed_in? && Like.find_by(user_id: current_user.id, item_id: @item.id) %> 
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <%= link_to "お気に入りから削除", item_like_path(@item, @item.likes), method: :delete %>
        <% else %>
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <%= link_to "お気に入り", item_likes_path(@item, @like), method: :post %>
        <% end %>
      </button>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <% if user_signed_in? && @item.order == nil  %>
      <%= form_with(model: [@item, @comment], local: true) do |form| %>
        <%= form.text_area :text, class: "comment-text" %>
        <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <button class="comment-btn">
          <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <%= form.submit "コメントする", class: "comment-btn" %>
        </button>
      <% end %>
    <% end %>

    <div class="comments">
      <h4>【コメント一覧】</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment">
            <div class="upper-comment">
              <div class="comment-user">
                <strong><%= comment.user.nickname %>：</strong>
              </div>
              <div class="comment-date">
                <%= l comment.created_at %>
              </div>
            </div>
            <div class="comment-text">
              <%= comment.text %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>  
  </div>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>